apiVersion: v1
kind: Service
metadata:
  name: questshift-llm
  labels:
    app: questshift-llm
    app.kubernetes.io/part-of: questshift
spec:
  selector:
    app: questshift-llm
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: questshift-engine
  labels:
    app: questshift-engine
    app.kubernetes.io/part-of: questshift
spec:
  selector:
    app: questshift-engine
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: questshift-ui
  labels:
    app: questshift-ui
    app.kubernetes.io/part-of: questshift
spec:
  selector:
    app: questshift-ui
  ports:
    - name: http
      port: 8080
      targetPort: http
