apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: questshift
commonLabels:
  app.kubernetes.io/part-of: questshift
resources:
  - pvc.yaml
  - configmap.yaml
  - llm-deployment.yaml
  - game-backend-deployment.yaml
  - game-ui-deployment.yaml
  - game-service.yaml
  - openshift-route.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: questshift-campaigns
    files:
      - campaigns/campaign-devops-dungeon.yaml
