apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: questshift
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: questshift
spec:
  project: default
  source:
    repoURL: https://github.com/NA-FSI-Services/questshift-gitops
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: questshift
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
